# packages/surveillance_prises_zigbee.yaml
# 📦 Package : Surveillance des prises Zigbee
# Auteur : [loic38100]
# Version : 1.0
# Description :
#   - Alerte si une prise est KO (off/unavailable/unknown)
#   - Notification de retour OK
#   - Rapport quotidien (22h)
#   - Vérif périodique (toutes les 5 min)
#   - Vérif au démarrage (même si déjà KO)
homeassistant:
  customize: {}

group:
  prises_zigbee:
    name: "Prises Zigbee surveillées"
    entities:
      - switch.refrigerateur
      - switch.cav
      - switch.congelateur

template:
  - binary_sensor:
      - name: "Prises Zigbee - État global"
        unique_id: prises_zigbee_etat_global
        icon: mdi:power-plug
        state: >
          {% set membres = expand('group.prises_zigbee') | list %}
          {% if not membres %}
            false
          {% else %}
            {{ membres | selectattr('state','in',['off','unavailable','unknown']) | list | count == 0 }}
          {% endif %}

automation:
  # 1) Alerte si au moins UNE prise est off/unavailable/unknown ≥ 5 min
  - id: alerte_prises_zigbee_probleme
    alias: "Alerte | Prises Zigbee en anomalie"
    mode: single
    trigger:
      - platform: template
        value_template: >
          {{ expand('group.prises_zigbee')
             | selectattr('state','in',['off','unavailable','unknown'])
             | list | count > 0 }}
        for: "00:05:00"
    action:
      - service: script.notifier_mogo_loic
        data:
          title: "⚠️ Prise Zigbee en anomalie"
          message: >
            {% for e in expand('group.prises_zigbee') if e.state in ['off','unavailable','unknown'] -%}
            ⚠️ {{ e.name }} n'est plus alimenté
            {% endfor %}

  # 2) Message de rétablissement quand tout redevient OK (≥ 2 min)
  - id: info_prises_zigbee_retablies
    alias: "Info | Prises Zigbee rétablies"
    mode: single
    trigger:
      - platform: template
        value_template: >
          {{ expand('group.prises_zigbee')
             | selectattr('state','in',['off','unavailable','unknown'])
             | list | count == 0 }}
        for: "00:02:00"
    action:
      - service: script.notifier_mogo_loic
        data:
          title: "✅ Prises Zigbee OK"
          message: "Toutes les prises surveillées sont revenues à l'état normal depuis 2 minutes."

  # 3) Rapport quotidien à 22:00
  - id: rapport_quotidien_prises_zigbee
    alias: "Rapport quotidien | Prises Zigbee"
    mode: single
    trigger:
      - platform: time
        at: "22:00:00"
    variables:
      defauts: >
        {{ expand('group.prises_zigbee')
           | selectattr('state','in',['off','unavailable','unknown'])
           | map(attribute='name') | list }}
      resume: >
        {% for e in expand('group.prises_zigbee') -%}
        {{ '\n' -}}• {{ e.name }} → {{ e.state }}
        {%- endfor %}
    action:
      - service: script.notifier_mogo_loic
        data:
          title: "📝 Rapport prises Zigbee (22:00)"
          message: >
            {{ '✅ Aucune anomalie détectée.' if defauts | count == 0
               else '⚠️ Anomalies : ' ~ (defauts | join(', ')) }}
            {{ '\n\nÉtat détaillé :' ~ resume }}

  # 4) Vérification périodique (toutes les 5 min) - immédiate
  - id: verif_periodique_prises_zigbee_5min
    alias: "Vérif périodique | Prises Zigbee (toutes les 5 min)"
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/5"

    condition:
      - condition: template
        value_template: >
          {{ expand('group.prises_zigbee')
             | selectattr('state','in',['off','unavailable','unknown'])
             | list | count > 0 }}

#    action:
#      - service: persistent_notification.create
#        data:
#          title: "DEBUG Vérif périodique Zigbee"
#          message: >
#            {% set defauts = expand('group.prises_zigbee')
#               | selectattr('state','in',['off','unavailable','unknown'])
#               | list %}
#            Détections :
#            {% for e in defauts -%}
#            \n• {{ e.name }} ({{ e.entity_id }})
#            {% endfor %}

      - service: script.notifier_mogo_loic
        data:
          title: "⚠️ Vérification périodique"
          message: >
            {% set defauts = expand('group.prises_zigbee')
               | selectattr('state','in',['off','unavailable','unknown'])
               | list %}
            {% for e in defauts -%}
            ⚠️ {{ e.name }} n'est plus alimenté
            {% endfor %}

  # 5) Vérif au démarrage (notification même si déjà KO)
  - id: verif_demarrage_prises_zigbee
    alias: "Vérif au démarrage | Prises Zigbee"
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: "00:01:30"  # ou "00:05:00" si tu préfères attendre 5 min
      - variables:
          en_defaut: >
            {% set membres = expand('group.prises_zigbee') %}
            {% set defauts = [] %}
            {% for e in membres if e.state in ['off','unavailable','unknown'] %}
              {% set _ = defauts.append(e) %}
            {% endfor %}
            {{ defauts }}
      - condition: template
        value_template: "{{ en_defaut | count > 0 }}"
      - service: script.notifier_mogo_loic
        data:
          title: "⚠️ Démarrage HA : anomalie prise Zigbee"
          message: >
            {% for e in en_defaut -%}
            ⚠️ {{ e.name }} n'est plus alimenté
            {% endfor %}
